-- 코드를 작성해주세요
SELECT i1.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO i1
JOIN ITEM_TREE t1 ON i1.ITEM_ID = t1.ITEM_ID  -- 모든 아이템
LEFT JOIN ITEM_TREE t2 ON t1.ITEM_ID = t2.PARENT_ITEM_ID  -- 나를 부모로 하는 자식들
WHERE t2.PARENT_ITEM_ID IS NULL  -- 자식이 없는 놈들만
ORDER BY i1.ITEM_ID DESC;