-- 코드를 작성해주세요
SELECT e.ID, e.GENOTYPE, p.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA e
JOIN ECOLI_DATA p
ON p.ID = e.PARENT_ID
WHERE e.PARENT_ID IS NOT NULL
AND e.GENOTYPE & p.GENOTYPE = p.GENOTYPE
ORDER BY e.ID ASC;
